services:
  - type: web
    name: leitor-pdf
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn leitorpdf.wsgi:application --bin